### ISSUE TITLE
Server doesn't work on linux

### ISSUE THREAD

**Issue by Minfrog314** [ReadOnly-Mods/Galacticraft-Pack#16]
## Bug Description

The script that installs/runs the server for linux doesn't work at all. It calls a function called install_server which seems specific to some other system. After modifying the script and manually installing the forge server, I got the server to run, but it crashes. I have tried with Java 8 and 11, on macos and linux (manjaro).

### Did this work in the previous version?

No

## Steps to Reproduce (for bugs)

1. Download the server zip from the curseforge page
2. Unzip it and run the script
3. It will output quite a few errors over and over
4. Install a forge server and add the mods, configs, and scripts from the server zip to it
5. Run java -jar -Xmx6G forge-1.12.2-14.23.5.2855.jar nogui
6. It crashes

## Logs

* Client/Server Log: https://pastebin.com/zY0bM1F1 (Note that this is with the default script, I have deleted the modified script when reinstalling, but I could do it again if needed.)
* Crash Log: https://pastebin.com/gRGLbg9y

## Client Information
* Modpack Version: 3.2.1
* Launcher Used: It is a Server.

* Java Version:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## World Information
* Modpack Version world created in: no world
* Additional Content Installed: none

## Server Information
* Java Version: openjdk version "1.8.0_282" ,OpenJDK Runtime Environment (build 1.8.0_282-b08), OpenJDK 64-Bit, Server VM (build 25.282-b08, mixed mode)
* Operating System: Manjaro Linux
* Hoster/Hosting Solution: Local
* Sponge (Non-Vanilla Forge) Server: none

**Comment by ROMVoid95** [comment]
Sorry this took longer than intended. 
The crash is caused by galacticraft-rpc mod accidently being included in the mods folder, i've reuploaded a fixed version of the server with it removed
[Updated  Server  File](https://www.curseforge.com/minecraft/modpacks/galacticraft-pack/files/3295866)

As for the scripts. I cannot really test them on Mac since and didn't plan on this. The distro of linux you mentioned is not one that i tested the bash script with so unless that distro  handles things differently (on a small VM test I performed it appears so but still not sure)

the scripts themselves are not required to  run the server, there only provided as a convenience. And if not needed or wouldn't work. the server can be installed using the supplied installer (which i assume you used). But seeing this ill think of a different way to package scripts / helpers in a later release.

**Comment by Minfrog314** [comment]
Ok, thank you for the fix.
